# Generated by Django 2.2.7 on 2019-11-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
